### ISSUE TITLE
Recurring Blockouts in Scheduler

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#171]
Setting a recurring blockout time using Start Date and End Date does not behave as expected. This sequence seems to be the only way to set a recurring blockout time:

1. Uncheck "All Day"
2. Set Start/End Time
3. Set Repeat

Setting a specific blockout time using start date/end date does not work as expected.
<img width="300" alt="Screen Shot 2019-05-05 at 3 14 10 PM" src="https://user-images.githubusercontent.com/50156267/57200422-14933c00-6f49-11e9-8433-df1568efd6fe.png">
<img width="799" alt="Screen Shot 2019-05-05 at 3 13 27 PM" src="https://user-images.githubusercontent.com/50156267/57200423-14933c00-6f49-11e9-9092-6ff4cf22e381.png">
<img width="312" alt="Screen Shot 2019-05-05 at 3 12 45 PM" src="https://user-images.githubusercontent.com/50156267/57200424-14933c00-6f49-11e9-9915-63baa90cdbff.png">
<img width="797" alt="Screen Shot 2019-05-05 at 3 12 09 PM" src="https://user-images.githubusercontent.com/50156267/57200425-14933c00-6f49-11e9-896b-82eddb0de497.png">

**Comment by benjaminwood** [comment]
@sarahwicks looking at the screenshots and the blockouts generated, I believe that the system is behaving as designed in both cases. The issue with the recurring blockout is that it spans multiple days, but is set to repeat every day which is logically problematic.

We modeled the blockout scheduling feature after planning center. Are you by chance familiar with that system? If not, I may be able to invite you so you can take a look (if it is helpful). Here's a screenshot with similar options selected and a similar result:  

![image](https://user-images.githubusercontent.com/1232531/58337724-45a1b680-7dfb-11e9-88d0-18ae44a200f5.png)

![image](https://user-images.githubusercontent.com/1232531/58337812-74b82800-7dfb-11e9-9d46-17f2193986fd.png)

The scheduling feature is extremely flexible, but can also be confusing. Perhaps we should consider dumbing it down a bit so that it's not so easy to shoot yourself in the foot. Thoughts?

Let me know if you'd like to chat about this on a call. If there is still confusion (including perhaps my own) about how the feature works and what is expected of it, it'll be a lot easier to get to the bottom of the matter if we can investigate together.

**Comment by sarahwicks** [comment]
@benjaminwood I'll take you up on a call - I think this is an important part of the UI, so I want to make sure it's intuitive but I definitely understand the desire to keep it flexible from a dev perspective. I can meet most days from 2 p.m. PST and beyond. Let me know what works for you and we can set up something. Perhaps you can show me the staging environment in the same call? cc: @SarahOMD @DarcyBlank if either/both of you want to be included

**Comment by benjaminwood** [comment]
@sarahwicks, thanks! I'll shoot you an email regarding scheduling a call to chat about this. One thing I'd like to clarify:

> but I definitely understand the desire to keep it flexible from a dev perspective

I believe you were referencing my comment:

> The scheduling feature is extremely flexible, but can also be confusing. Perhaps we should consider dumbing it down a bit so that it's not so easy to shoot yourself in the foot. Thoughts?

I meant that the scheduling feature is extremely flexible from a users perspective, not a dev perspective. I believe that the UX could be simplified by limiting what is possible, whereas right now, just about anything is possible.
